Repository ITISFoundation/osparc-deployment-agent, pull requests merged in 2023-03, with the labels that each got.

#155 Fix/portainer incompatability and tests 🚧🚧🚧
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  requirements/_base.in
  requirements/_base.txt
  requirements/_test.in
  requirements/_test.txt
  requirements/_tools.txt
  src/simcore_service_deployment_agent/git_url_watcher.py
  src/simcore_service_deployment_agent/portainer.py
  tests/conftest.py
  tests/fixtures/fixture_portainer.py
  tests/integration/test_with_portainer_service.py
  tests/mocks/valid_docker_stack_local_registry.yaml
  tests/unit/test_git_url_watcher.py
  tests/unit/test_portainer.py
Labels: enhancement, EPIC

#149 ✨ ♻️ GitUrlWatcher keeps state and extra tag info
  .gitignore
  .vscode/extensions.json
  .vscode/launch.template.json
  Makefile
  mypy.ini
  requirements/devenv.txt
  scripts/mypy.bash
  scripts/mypy/Dockerfile
  scripts/mypy/requirements.txt
  setup.cfg
  src/simcore_service_deployment_agent/auto_deploy_task.py
  src/simcore_service_deployment_agent/cmd_utils.py
  src/simcore_service_deployment_agent/git_url_watcher.py
  src/simcore_service_deployment_agent/subtask.py
  tests/unit/test_auto_deploy_task.py
  tests/unit/test_cmd_utils.py
  tests/unit/test_git_url_watcher.py
Labels: enhancement

#156 Add/git repo tag sync 🚧🚧🚧
  Makefile
  deployment_config.template.yaml
  src/simcore_service_deployment_agent/config_schema.py
  src/simcore_service_deployment_agent/git_url_watcher.py
  tests/integration/test_with_portainer_service.py
  tests/mocks/valid_config.yaml
  tests/mocks/valid_config_no_notification.yaml
  tests/mocks/valid_system_test_config.yaml
  tests/unit/test_docker_registries_watcher.py
  tests/unit/test_git_url_watcher.py
  tests/unit/test_portainer.py
  tests/unit/test_rest.py
Labels: enhancement, EPIC

#169 Fix/bug tag sync
  Makefile
  src/simcore_service_deployment_agent/auto_deploy_task.py
  src/simcore_service_deployment_agent/config_schema.py
  src/simcore_service_deployment_agent/exceptions.py
  src/simcore_service_deployment_agent/git_url_watcher.py
  src/simcore_service_deployment_agent/portainer.py
  src/simcore_service_deployment_agent/subprocess_utils.py
  tests/conftest.py
  tests/mocks/valid_config_variation.yaml
  tests/unit/test_git_url_watcher.py
Labels: bug

#173 🐛 Fixes: Bugs observed during Mithril1 prerelease
  src/simcore_service_deployment_agent/auto_deploy_task.py
  src/simcore_service_deployment_agent/git_url_watcher.py
Labels: bug
